mysql:
  host: 'mysql_db'
  port: 3306
  user: 'root'
  password: 'admin'

clickhouse:
  host: 'clickhouse_db'
  port: 9123
  user: 'default'
  password: 'admin'

binlog_replicator:
  data_dir: '/app/binlog/'
  records_per_file: 100000
  binlog_retention_period: 43200  # 12 hours in seconds

databases: '*test*'
log_level: 'debug'
optimize_interval: 3
check_db_updated_interval: 3

# This mapping is the key part that causes issues with schema evolution
target_databases:
  replication-test_db: mapped_target_db

http_host: '0.0.0.0'
http_port: 9128 